version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USERNAME: root
      DB_PASSWORD: secret
    volumes:
      - ./backend:/var/www/html
    restart: unless-stopped

  frontend-sme:
    build: ./frontend-sme
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend-sme:/app      # bind mount → sync กับ local
      - /app/node_modules     # ป้องกัน node_modules conflict
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true  # ช่วยให้ hot reload ทำงานบน Docker ได้ดีขึ้น

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret

volumes:
  mysql_data:
